/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PasajeroControlador;
import javax.swing.JFrame;
import controlador.RutaControlador;
import controlador.ViajeControlador;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DecimalFormat;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Pasajero;

import modelo.Ruta;
import modelo.Viaje;
/**
 *
 * @author RONALD
 */
public class VendedorForm extends javax.swing.JFrame {
 
    private ViajeControlador viajeDAO = new ViajeControlador();
    private RutaControlador rutaDAO = new RutaControlador();
    private DefaultTableModel modeloTabla;
    
    private PasajeroControlador pasajeroDAO = new PasajeroControlador();
    private DefaultTableModel tableBoletos;
    
    public VendedorForm() {
        initComponents();
        setTitle("PERÚBUSS - Vendedor");
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        modeloTabla = (DefaultTableModel) tablaViajes.getModel();
 
        cargarRutas(); // Llena el JComboBox con las rutas
        cargarViajes(); // Carga todos los viajes al iniciar

        // Evento cuando se selecciona una ruta
        cbRutas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarViajes();
                String seleccion = (String) cbRutas.getSelectedItem();
                if (!"Todas".equals(seleccion)) {
                    System.out.println("carga: "+seleccion);
                    cargarImagenRuta(seleccion);
                } else {
                    lblImagenRuta.setIcon(null); // Limpiar si es "Todas"
                }
            }
        });
        
        tableBoletos = (DefaultTableModel) tablePasajeros.getModel();
        List<Pasajero> pasajeros = pasajeroDAO.obtenerPasajerosDeBoletos();
        tableBoletos.setRowCount(0);
        for (Pasajero pasajero : pasajeros) {
            tableBoletos.addRow(new Object[]{ 
                pasajero.getBOLNRO(),
                pasajero.getNOMPASA(),  
                pasajero.getNROASIE(),
                pasajero.getTIPO(),
                pasajero.getPAGO()
            }); 
        }
    }
     
    private void cargarRutas() {
        cbRutas.removeAllItems(); // Limpiar opciones
        cbRutas.addItem("Todas"); // Opción para mostrar todo

        List<Ruta> rutas = rutaDAO.obtenerRutas();
        for (Ruta ruta : rutas) {
            cbRutas.addItem(ruta.getRUTNOM()); // Mostrar el destino en el ComboBox
        }
    }

    private void cargarViajes() {
        modeloTabla.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos
        String seleccion = (String) cbRutas.getSelectedItem();
        List<Viaje> viajes;

        if ("Todas".equals(seleccion)) {
            viajes = viajeDAO.obtenerTodos();
        } else {
            String codRuta = rutaDAO.obtenerCodigoPorNombre(seleccion);
            viajes = viajeDAO.obtenerPorRuta(codRuta);
        }

        for (Viaje v : viajes) {
            modeloTabla.addRow(new Object[]{
                v.getVIANRO(),
                v.getVIAFCH(),
                v.getVIAHRS(),
                v.getBUSNRO()
            });
        }
    } 
    
    private void cargarImagenRuta(String destino) {
        String rutaImagen = "src/main/java/img/turismo/" + destino + ".jpg"; // Ruta de la imagen
        File archivo = new File(rutaImagen);
        
        System.out.println("Ruta imagen: " + archivo.getAbsolutePath());

        if (archivo.exists()) {
            ImageIcon icono = new ImageIcon(rutaImagen);
            Image imagen = icono.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH); // Ajustar tamaño
            lblImagenRuta.setIcon(new ImageIcon(imagen));
        } else {
            lblImagenRuta.setIcon(null); // Limpiar si no hay imagen
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaViajes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblIdRuta = new javax.swing.JLabel();
        lblImagenRuta = new javax.swing.JLabel();
        cbRutas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblBOLNRO = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePasajeros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ViaNro", "Fecha", "Hora", "Bus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaViajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaViajes);

        jLabel1.setText("Seleccione Ruta");

        lblImagenRuta.setText(".");

        cbRutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblIdRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblImagenRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagenRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdRuta)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Viajes ", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar Boleta:");

        lblBOLNRO.setText("000010");

        tablePasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NRO VIAJE", "PASAJERO", "ASIENTO", "TIPO", "PAGO", "OPCIONES"
            }
        ));
        jScrollPane2.setViewportView(tablePasajeros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBOLNRO, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3)
                    .addComponent(lblBOLNRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String idRutaSeleccionada;
    private void tablaViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaViajesMouseClicked
        if (evt.getClickCount() == 1) {
            int filaSeleccionada = tablaViajes.getSelectedRow();

            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(this, "Selecciona una ruta válida", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Object valor = tablaViajes.getValueAt(filaSeleccionada, 0);

            if (valor != null) {
                idRutaSeleccionada = valor.toString(); 
                VendedorFormVenta formvendedor = new VendedorFormVenta(idRutaSeleccionada);
                formvendedor.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo obtener el ID de la ruta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tablaViajesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cd = lblBOLNRO.getText();
        tableBoletos.setRowCount(0);
        List<Pasajero> pasajeros = pasajeroDAO.obtenerPasajerosPorBoleto(cd);

        for (Pasajero pasajero : pasajeros) {
            tableBoletos.addRow(new Object[]{ 
                pasajero.getBOLNRO(),
                pasajero.getNOMPASA(),  
                pasajero.getNROASIE(),
                pasajero.getTIPO(),
                pasajero.getPAGO()
            }); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendedorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbRutas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lblBOLNRO;
    private javax.swing.JLabel lblIdRuta;
    private javax.swing.JLabel lblImagenRuta;
    private javax.swing.JTable tablaViajes;
    private javax.swing.JTable tablePasajeros;
    // End of variables declaration//GEN-END:variables
}
